### ISSUE TITLE
[TALENT] Shadow Focus | Rogue

### ISSUE THREAD

**Issue by YukkiKun** [ProjectSkyfire/SkyFire_548#1033] opened 2021-03-02 05:00 UTC
**Description:**

Shadow Focus is a level 15 talent.

**Current behaviour:**

Shadow Focus is not working at all

**Expected behaviour:**

When you get Shadow Focus talent, abilitied shound cost 75% less energy while stealthed.

**Comment by lingxDEV** [comment] 2021-03-02 14:33
duplicate of #921

**Closed** 2021-03-08 13:21 UTC
